name: Node.js CI

on: [push, pull_request]

env: 
    DATABASE_URL: https://snap-nine.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: TypeScript type checking
        run: npm run typecheck

      - name: Run lint
        run: npm run lint
